apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: devops-lab-deploy
spec:
  selector:
    matchLabels:
      app: devops-lab
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: devops-lab
    spec:
      containers:
        - name: devops-lab
          image: claudiopizarro/devops-lab:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # The port that the container is running on in the cluster
