apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: devops-lab-ssvc
spec:
  selector:
    app: devops-lab
  ports:
    - protocol: "TCP"
      port: 3000 
      targetPort: 3000 
  type: LoadBalancer # type of the service.