apiVersion: v1
kind: Service
metadata:
  name: devops-lab-service
  namespace: jenkins
spec:
  selector:
    app: devops-lab
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000  # Elige un puerto entre 30000-32767
  type: NodePort
